version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: clinicbot_postgres
    restart: always
    environment:
      POSTGRES_USER: clinicbot_user
      POSTGRES_PASSWORD: clinicbot_password
      POSTGRES_DB: clinicbot_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
